name: CD
run-name: Continuos Deploy
on: 
    push: 
        branches: 
            - main
permissions: 
    contents: write
jobs:
    Build:
      runs-on: ubuntu-latest
      # permissions:  
      steps:
        - name: Check_Page
          uses: actions/checkout@v4
        
        - name: Upload_Do_Aterfato
          # id: build
          uses: actions/upload-pages-artifact@v3
          with: 
            path: src/

    Deploy:
        runs-on: ubuntu-latest
        needs: Build
        permissions: 
          pages: write
          id-token: write
        steps:
            - name: Check_Page
              uses: actions/checkout@v4

            # - name: Deploy_Page
            #   uses: JamesIves/github-pages-deploy-action@v4.6.9
            #   with:
            #       folder: src
            # - name: Deploy_Certo
            #   uses: peaceiris/actions-gh-pages@v4
            #   with: 
            #     #falta o token // MÃO TEM A CERTIFICAÇÃO 
            #     publish_dir: ./public  

            - name: Deploy_Mais_Certo
              uses: actions/deploy-pages@v4.0.5
              with:
                  token: ${{github.token}}