name: CD
run-name: Continuos Deploy
on: 
    push: 
        branches: 
            - main

permissions: 
    contents: write

jobs:
    #Trabalho
    Build:
      runs-on: ubuntu-latest
      steps:
        - name: Check_Page
          uses: actions/checkout@v4
        
        - name: Upload_Do_Aterfato
          uses: actions/upload-pages-artifact@v3
          with: 
            path: src/

    Deploy:
        runs-on: ubuntu-latest
        needs: Build
        environment: 
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
        permissions: 
          pages: write
          id-token: write
        steps:
            - name: Check_Page
              uses: actions/checkout@v4

            - name: Deploy_Mais_Certo
              id: deployment
              uses: actions/deploy-pages@v4.0.5
              with:
                  token: ${{github.token}}