name: CD
run-name: Continuos Deploy
on: 
    push: 
        branches: 
            - main
permissions: 
    contents: write
jobs:
    Continuos_Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Check_Page
              uses: actions/checkout@v4

            - name: Deploy_Page
              uses: JamesIves/github-pages-deploy-action@v4.6.9
              with:
                  folder: src 

            - name: Deploy_Certo
              uses: peaceiris/actions-gh-pages@v4
              with: 
                publish_dir: ./public