name: CD
run-name: Continuos Deploy
on: 
    push: 
        branches: 
            - main
jobs:
    Continuos_Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy_Page
              uses: JamesIves/github-pages-deploy-action@v4.6.9
              with:
                  folder: src 