name: Linkar Cartão
run-name: Linkar Cartão
on: 
    pull_request
jobs:
  Link-Trello-Card:
    runs-on: ubuntu-latest
    steps:
        - run: echo "ado a"
        - name: checar_o_codigo
          uses: actions/checkout@v3
        - name: pegar_o_valor_depois_de_-pr#
          run: |
            PR_TITLE="${{ github.event.pull_request.title }}"
            if [[ $PR_TITLE =~ -tc#([0-9]+) ]];s then
               echo "tc_number=${BASH_REMATCH[1]}" >> $GITHUB_ENV
            else
               echo "tc_number=not_found" >> $GITHUB_ENV
            fi
        - name: printar_o_valor_em_outro_step
          run: echo "o valor que foi enviado é $tc_number"