name: Context testing
on: push

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: GitHub
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_
        
      - name: Dump job context
        id: job
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_
        
      - name: Dump steps context
        id: steps
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_
        
      - name: Dump runner context
        id: runner
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_
        
      - name: Dump strategy context
        id: strategy
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_
        
      - name: Dump matrix context
        id: matrix
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_
        